import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("inventory pricing adds a sheet menu without a second onOpen", () => {
  const menu = readFileSync(new URL("../apps-script/NIP_Menu.gs", import.meta.url), "utf8");
  const api = readFileSync(new URL("../apps-script/NIP_Api.gs", import.meta.url), "utf8");
  const code = readFileSync(new URL("../apps-script/Code.gs", import.meta.url), "utf8");
  const manifest = readFileSync(new URL("../apps-script/appsscript.json", import.meta.url), "utf8");
  assert.match(manifest, /script\.external_request/);
  assert.match(api, /algoliaConfig/);
  assert.match(code, /\{ title: 'New Inventory Pricing', onOpen: 'NIP_onOpen' \}/);
  assert.equal(code.split("\n").filter((line) => line.startsWith("function onOpen(")).length, 1);
  assert.match(menu, /function NIP_onOpen\(/);
  assert.match(menu, /addItem\('Geaux Chevy', 'GCY_open'\)/);
  assert.match(menu, /addItem\('Web app link', 'NIP_showWebAppUrl'\)/);
  assert.doesNotMatch(menu, /Compare discounts/);
  assert.match(menu, /showModalDialog/);
  assert.doesNotMatch(menu, /function onOpen\(/);
  const chevyMenu = readFileSync(new URL("../apps-script/GCY_Menu.gs", import.meta.url), "utf8");
  const chevyApi = readFileSync(new URL("../apps-script/GCY_Api.gs", import.meta.url), "utf8");
  assert.match(chevyMenu, /function GCY_open\(/);
  assert.match(chevyMenu, /GCY_App/);
  assert.doesNotMatch(chevyMenu, /function onOpen\(/);
  assert.doesNotMatch(chevyMenu, /function doGet\(/);
  assert.doesNotMatch(chevyApi, /function onOpen\(/);
  assert.doesNotMatch(chevyApi, /function doGet\(/);
  assert.doesNotMatch(chevyApi, /DEALINPUT/);
  assert.doesNotMatch(api, /function onOpen\(/);
  assert.doesNotMatch(api, /DEALINPUT/);
  assert.match(api, /dealer-incentive\|dealer-discount/);
  assert.match(api, /sitemap\.xml/);
});
